# Generated by Django 4.2.6 on 2023-10-18 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Software_Settings', '0002_module_sub_module'),
        ('HRM', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_create', models.BooleanField(default=False)),
                ('is_read', models.BooleanField(default=False)),
                ('is_update', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('Designation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM.designation')),
                ('module', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Software_Settings.module')),
                ('sub_module', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Software_Settings.sub_module')),
            ],
        ),
    ]
